### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ensure_text' after upgrade to 0.7.0

### ISSUE THREAD

**Issue by clauded** [ckan/ckanext-xloader#125]
After upgrading from 0.6.1 to 0.7.0 we have the following error in ou logs:

```
File "/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/loader.py", line 80, in load_csv
delimiter = sniffer.sniff(six.ensure_text(header_line)).delimiter
AttributeError: 'module' object has no attribute 'ensure_text'
```

Updating the python module **six** to the latest version (1.15.x) fixes the issue. 

Maybe the file **requirements.txt** should specify a minimum version for six?
